services:
  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - grafana-storage:/var/lib/grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=your_secure_password
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
  app_1:
    image: bloomnode:latest
    ports:
      - "8000:8000"
      - "9000:9000"
  app_2:
    image: bloomnode:latest
    ports:
      - "8001:8000"
      - "9001:9000"
  app_3:
    image: bloomnode:latest
    ports:
      - "8002:8000"
      - "9002:9000"
  app_4:
    image: bloomnode:latest
    ports:
      - "8003:8000"
      - "9003:9000"
volumes:
  grafana-storage:
  prometheus_data: